In [1]:
import os
import folium

print(folium.__version__)

0.7.0


In [54]:
import numpy as np
import pandas as pd
data = (
    np.random.normal(size=(10000, 3)) *
    np.array([[1, 1, 1]]) +
    np.array([[48, 5, 1]])
).tolist()
print(    np.random.normal(size=(10000, 3)) *
    np.array([[1, 1, 1]]) +
    np.array([[48, 5, 1]]))

[[48.84127876  5.14240209  1.58522544]
 [48.05400072  5.93618094 -0.31221399]
 [47.71322139  4.68463909  1.44055406]
 ...
 [47.83800403  4.60519778  2.20229595]
 [48.57840505  4.09833878  0.24984634]
 [47.60824948  4.61681563  1.54387871]]


In [124]:
import imgkit

In [109]:
from folium.plugins import HeatMap

m = folium.Map([30.508154, 114.418808],  zoom_start=14)

HeatMap(Map_data).add_to(m)

#m.save(os.path.join('results', 'Heatmap.html'))

m

In [43]:
data = pd.read_csv("E:\\graduate\\Mobike\\data\\20180901-000851-027.csv")
print(data.info())
data.columns = ["time", "ID", "lng","lat"]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 273271 entries, 0 to 273270
Data columns (total 4 columns):
2018-09-01 00:07:53    273271 non-null object
8621109031#            273271 non-null object
113.96863535427319     273271 non-null float64
30.676131178662434     273271 non-null float64
dtypes: float64(2), object(2)
memory usage: 8.3+ MB
None


In [103]:
Map_data = []
for x in range(0, 100):
    for y in range(0, 100):
        Map_data.append([min_lat + dlat*y, min_lng + dlng*x, Map[x][y]/50000])

In [33]:
print("lng: %f %f %f" % (max(data.lng), min(data.lng), max(data.lng)- min(data.lng)))
print("lat: %f %f %f" % (max(data.lat), min(data.lat), max(data.lat)- min(data.lat)))

lng: 114.611238 113.919177 0.692061
lat: 30.785815 30.236908 0.548907


In [3]:
import numpy as np
import pandas as pd
import os
import folium
data = pd.read_csv("E:\\graduate\\Mobike\\data\\20180901-115849-027.csv")
data.columns = ["time", "ID", "lng","lat"]
#max_lng, min_lng = max(data.lng), min(data.lng)
#max_lat, min_lat = max(data.lat), min(data.lat)
max_lng, max_lat = 114.462789,30.53242
min_lng, min_lat = 114.377558,30.48774
dlng, dlat = (max_lng - min_lng)/100, (max_lat - min_lat)/100
#print("dlng: %f dlat: %f" % (dlng, dlat))

Map = np.zeros((100,100), dtype = np.int)

def count(df):
    x = int((df['lng'] - min_lng) / dlng) - 1
    y = int((df['lat'] - min_lat) / dlat) - 1
    if x >= 0 and x <= 99 and y >= 0 and y <= 99:
        Map[x][y] += 1

from sklearn import preprocessing
max_abs_scaler = preprocessing.MaxAbsScaler()
#Map = max_abs_scaler.fit_transform(Map)
data.apply(count, axis = 1)

Map_data = []
for x in range(0, 100):
    for y in range(0, 100):
        Map_data.append([min_lat + dlat*y, min_lng + dlng*x, Map[x][y] - 4 if Map[x][y] - 4 > 0 else 0])
        
from folium.plugins import HeatMap

m = folium.Map([30.508154, 114.418808], zoom_start=14)

HeatMap(Map_data).add_to(m)
#m.save(os.path.join('results', 'C:\\Users\\Wang\\Desktop\\heatp\\Heatmap.html'))

# m.save('C:\\Users\\Wang\\Desktop\\heatp\\Heatmap.html')

m

FileNotFoundError: File b'E:\\graduate\\Mobike\\data\\20180901-115849-027.csv' does not exist

In [1]:
import imgkit
config = imgkit.config(wkhtmltoimage='C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe')
#imgkit.from_url('http://www.baidu.com', 'D:\\out.jpg', config=config)
imgkit.from_file("C:\\Users\\Wang\\Desktop\\heatp\\Heatmap.html", "C:\\Users\\Wang\\Desktop\\heatp\\out.pdf", config=config)

OSError: No such file: C:\Users\Wang\Desktop\heatp\Heatmap.html

In [2]:

import matplotlib.pyplot as plt
import imageio,os
images = []
print(os.listdir( "C:\\Users\\Wang\\Desktop\\heatp\\GG"))
filenames=sorted((fn for fn in os.listdir( "C:\\Users\\Wang\\Desktop\\heatp\\GG")))

for filename in filenames:
    filename = "C:\\Users\\Wang\\Desktop\\heatp\\GG\\" + filename
    images.append(imageio.imread(filename))
imageio.mimsave("C:\\Users\\Wang\\Desktop\\heatp\\GG.gif", images,duration=1)


FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'C:\\Users\\Wang\\Desktop\\heatp\\GG'